server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ha1-microservice-sensor
          uri: lb://HA1-MICROSERVICE
          predicates:
            - Path=/sensors/**
        - id: ha1-microservice-measurement
          uri: lb://HA1-MICROSERVICE
          predicates:
            - Path=/measurements/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
