spring:
  application:
    name: configserver
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/username/reponame
          username: username
          password: pw
server:
  port: 8888
